version: "3.8"

services:
  nodejs:
    build: ./
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./:/app
    networks:
      - mynetwork
  mongodb:
    image: mongo:7.0
    ports:
      - 27017:27017
    volumes:
      - ../.mongodb/db:/data/db
    networks:
      - mynetwork

  redisdb:
    image: "redis:alpine"
    ports:
     - "6379:6379"
    volumes:
      - ../.redisdb/redis-data:/var/lib/redis
      - ../.redisdb/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - mynetwork

networks:
  mynetwork:
