version: "3.8"

services:
  nodejs:
    build: ./
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./:/app
    networks:
      - mynetwork

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - ../Jenkins/jenkins_home:/var/jenkins_home
    networks:
      - mynetwork

networks:
  mynetwork:
