pipeline {
    agent any

    stages {
        stage('Start Node.js Service') {
            steps {
                script {
                    sh 'docker-compose up -d nodejs'
                }
            }
        }
    }
}