pipeline {
    agent any

    environment {
        AWS_CREDENTIALS_ID = 'aws-ecr-credentials'
        AWS_REGION = 'us-east-1'
        ECR_REPO_NAME = 'public.ecr.aws/z7u2k1p5'
        ECR_IMAGE_NAME = 'images'
        IMAGE_TAG = 'latest'
        ACCOUNT_ID = '484056151642'
        GIT_URL = 'git@github.com:danielrrv/golden-goals-2024-02.git'
    }

    stages {

        stage('Checkout') {
            steps {
                echo 'Checking out source code...'
                git branch: 'main',
                url: GIT_URL,
                credentialsId: '7af5dfdf-1abd-4d79-8b71-d8835c94a254'
            }
        }

        stage('Install Dependencies') {
            steps {
                echo 'Installing dependencies...'
                sh 'pnpm install'
            }
        }

        stage('Code Quality') {
            steps {
                echo 'Running ESLint...'
                sh 'pnpm run lint'
            }
        }

        stage('Run Tests') {
            steps {
                echo 'Running tests...'
                sh 'pnpm test'
            }
            post {
                always {
                    junit 'test-results.xml'
                }
            }
        }

        stage('Login to AWS ECR') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: "${AWS_CREDENTIALS_ID}"
                ]]) {
                    sh """
                    aws ecr-public get-login-password --region ${AWS_REGION} | \\
                    docker login --username AWS --password-stdin ${ECR_REPO_NAME}
                    """
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t  images ."
            }
        }

         stage('Tag Docker Image') {
            steps {
                sh "docker tag images:latest ${ECR_REPO_NAME}/${ECR_IMAGE_NAME}:${IMAGE_TAG}"
            }
        }

        stage('Push to AWS ECR') {
            steps {
                sh "docker push ${ECR_REPO_NAME}/${ECR_IMAGE_NAME}:${IMAGE_TAG}"
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully! ;)'
        }
        failure {
            echo 'Pipeline failed. :('
        }
    }
}
